// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2) {
  return window['go']['auth']['AuthService']['AddUser'](arg1, arg2);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['auth']['AuthService']['ChangePassword'](arg1, arg2, arg3);
}

export function ConnectToPort(arg1) {
  return window['go']['auth']['AuthService']['ConnectToPort'](arg1);
}

export function Disconnect() {
  return window['go']['auth']['AuthService']['Disconnect']();
}

export function GetResponse(arg1) {
  return window['go']['auth']['AuthService']['GetResponse'](arg1);
}

export function ListPorts() {
  return window['go']['auth']['AuthService']['ListPorts']();
}

export function Login(arg1, arg2) {
  return window['go']['auth']['AuthService']['Login'](arg1, arg2);
}

export function RemoveUser(arg1) {
  return window['go']['auth']['AuthService']['RemoveUser'](arg1);
}

export function Send(arg1) {
  return window['go']['auth']['AuthService']['Send'](arg1);
}
