// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';

export function AddUser(arg1:string,arg2:string):Promise<void>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectToPort(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetCurrentPort():Promise<string>;

export function GetResponse(arg1:time.Duration):Promise<string>;

export function ListPorts():Promise<Array<string>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function RemoveUser(arg1:string):Promise<void>;

export function Send(arg1:string):Promise<void>;
