// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPort(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ListPorts():Promise<Array<string>>;

export function Read():Promise<string>;

export function Send(arg1:string):Promise<void>;
