// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPort(arg1) {
  return window['go']['auth']['AuthService']['ConnectToPort'](arg1);
}

export function Disconnect() {
  return window['go']['auth']['AuthService']['Disconnect']();
}

export function ListPorts() {
  return window['go']['auth']['AuthService']['ListPorts']();
}

export function Send(arg1) {
  return window['go']['auth']['AuthService']['Send'](arg1);
}
