// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calib16ma() {
  return window['go']['control']['ControlService']['Calib16ma']();
}

export function Calib4ma() {
  return window['go']['control']['ControlService']['Calib4ma']();
}

export function GetNetworkInfo() {
  return window['go']['control']['ControlService']['GetNetworkInfo']();
}

export function ReadAnalog() {
  return window['go']['control']['ControlService']['ReadAnalog']();
}

export function ReadMemoryView() {
  return window['go']['control']['ControlService']['ReadMemoryView']();
}

export function ReadTagView() {
  return window['go']['control']['ControlService']['ReadTagView']();
}

export function SetTime(arg1) {
  return window['go']['control']['ControlService']['SetTime'](arg1);
}

export function SettingNetwork(arg1) {
  return window['go']['control']['ControlService']['SettingNetwork'](arg1);
}
