// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calib16ma() {
  return window['go']['control']['ControlService']['Calib16ma']();
}

export function Calib4ma() {
  return window['go']['control']['ControlService']['Calib4ma']();
}

export function GetNetworkInfo() {
  return window['go']['control']['ControlService']['GetNetworkInfo']();
}

export function Ping(arg1) {
  return window['go']['control']['ControlService']['Ping'](arg1);
}

export function ReadAnalog() {
  return window['go']['control']['ControlService']['ReadAnalog']();
}

export function ReadMemoryView() {
  return window['go']['control']['ControlService']['ReadMemoryView']();
}

export function ReadSdcardInfo() {
  return window['go']['control']['ControlService']['ReadSdcardInfo']();
}

export function ReadSimInfo() {
  return window['go']['control']['ControlService']['ReadSimInfo']();
}

export function ReadSystemInfo() {
  return window['go']['control']['ControlService']['ReadSystemInfo']();
}

export function ReadTagView() {
  return window['go']['control']['ControlService']['ReadTagView']();
}

export function Reboot() {
  return window['go']['control']['ControlService']['Reboot']();
}

export function ResetConfiguration() {
  return window['go']['control']['ControlService']['ResetConfiguration']();
}

export function SetDigitalOutput(arg1) {
  return window['go']['control']['ControlService']['SetDigitalOutput'](arg1);
}

export function SetTime(arg1) {
  return window['go']['control']['ControlService']['SetTime'](arg1);
}

export function SettingNetwork(arg1) {
  return window['go']['control']['ControlService']['SettingNetwork'](arg1);
}

export function StopReadAnalog() {
  return window['go']['control']['ControlService']['StopReadAnalog']();
}

export function StopReadMemoryView() {
  return window['go']['control']['ControlService']['StopReadMemoryView']();
}

export function StopReadTagView() {
  return window['go']['control']['ControlService']['StopReadTagView']();
}

export function WriteMacAddress(arg1) {
  return window['go']['control']['ControlService']['WriteMacAddress'](arg1);
}

export function WriteSerialNumber(arg1) {
  return window['go']['control']['ControlService']['WriteSerialNumber'](arg1);
}
