// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calib16ma():Promise<void>;

export function Calib4ma():Promise<void>;

export function GetNetworkInfo():Promise<void>;

export function ReadAnalog():Promise<void>;

export function ReadMemoryView():Promise<void>;

export function ReadTagView():Promise<void>;

export function SetTime(arg1:Array<number>):Promise<void>;

export function SettingNetwork(arg1:Record<string, any>):Promise<void>;

export function StopReadAnalog():Promise<void>;

export function StopReadMemoryView():Promise<void>;

export function StopReadTagView():Promise<void>;
