// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['workspace']['WorkspaceService']['DeleteFile'](arg1);
}

export function GetWorkspacePath() {
  return window['go']['workspace']['WorkspaceService']['GetWorkspacePath']();
}

export function ListFiles() {
  return window['go']['workspace']['WorkspaceService']['ListFiles']();
}

export function ReadFile(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['ReadFile'](arg1, arg2);
}

export function ShowInExplorer(arg1) {
  return window['go']['workspace']['WorkspaceService']['ShowInExplorer'](arg1);
}
