// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {context} from '../models';

export function Calibrate16mA(arg1:string,arg2:string):Promise<void>;

export function Calibrate4mA(arg1:string,arg2:string):Promise<void>;

export function ChangePassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CheckSocketConnection(arg1:string,arg2:string):Promise<boolean>;

export function ConnectSocket(arg1:string,arg2:string):Promise<string>;

export function CreateFolder(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function DisconnectSocket(arg1:string,arg2:string):Promise<void>;

export function DownloadConfig():Promise<void>;

export function DownloadConfigEthernet(arg1:string,arg2:string):Promise<void>;

export function ExportJSONFile(arg1:string,arg2:string):Promise<void>;

export function GetAllSocketData(arg1:string,arg2:string):Promise<Array<string>>;

export function GetDefaultData():Promise<string>;

export function GetMeasureMode(arg1:string,arg2:string):Promise<void>;

export function GetRTC(arg1:string,arg2:string):Promise<void>;

export function GetSocketData(arg1:string,arg2:string):Promise<string>;

export function GetWorkspacePath():Promise<string>;

export function ImportFileToFolderInWorkspace(arg1:string,arg2:string):Promise<void>;

export function ImportFileToWorkspace(arg1:string,arg2:string):Promise<void>;

export function ListActiveConnections():Promise<Array<string>>;

export function ListFiles():Promise<Array<workspace.FileNode>>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Logout(arg1:string,arg2:string):Promise<void>;

export function NewProject(arg1:string):Promise<void>;

export function Paste(arg1:string,arg2:string):Promise<void>;

export function PingDevice(arg1:string,arg2:string,arg3:string):Promise<void>;

export function QueryNetwork(arg1:string,arg2:string):Promise<void>;

export function ReadAnalog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadMemoryView(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReadSdCardInfo(arg1:string,arg2:string):Promise<void>;

export function ReadSimInfo(arg1:string,arg2:string):Promise<void>;

export function ReadSystemInfo(arg1:string,arg2:string):Promise<void>;

export function ReadTagView(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RebootDevice(arg1:string,arg2:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function ResetConfiguration(arg1:string,arg2:string):Promise<void>;

export function SaveJsonFile(arg1:string,arg2:string):Promise<void>;

export function SaveJsonToPath(arg1:string,arg2:string):Promise<void>;

export function SendSocketData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDigitalOutputEthernet(arg1:string,arg2:string,arg3:Array<boolean>):Promise<void>;

export function SetMeasureMode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRTC(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SettingNetworkEthernet(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function ShowInExplorer(arg1:string):Promise<void>;

export function UploadConfig(arg1:string):Promise<void>;

export function UploadConfigEthernet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteMacAddress(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteSerialNumber(arg1:string,arg2:string,arg3:string):Promise<void>;
