// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {context} from '../models';

export function CreateFolder(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function DowloadConfig():Promise<void>;

export function ExportJSONFile(arg1:string,arg2:string):Promise<void>;

export function GetWorkspacePath():Promise<string>;

export function ImportFile(arg1:string,arg2:string):Promise<void>;

export function ListFiles():Promise<Array<workspace.FileNode>>;

export function NewProject(arg1:string):Promise<void>;

export function Paste():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function SetClipboard(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ShowInExplorer(arg1:string):Promise<void>;
