// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSocketConnection(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['CheckSocketConnection'](arg1, arg2);
}

export function ConnectSocket(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['ConnectSocket'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['workspace']['WorkspaceService']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['workspace']['WorkspaceService']['DeleteFile'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['workspace']['WorkspaceService']['DeleteItem'](arg1);
}

export function DisconnectSocket(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['DisconnectSocket'](arg1, arg2);
}

export function DownloadConfig() {
  return window['go']['workspace']['WorkspaceService']['DownloadConfig']();
}

export function ExportJSONFile(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['ExportJSONFile'](arg1, arg2);
}

export function GetAllSocketData(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['GetAllSocketData'](arg1, arg2);
}

export function GetDefaultData() {
  return window['go']['workspace']['WorkspaceService']['GetDefaultData']();
}

export function GetSocketData(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['GetSocketData'](arg1, arg2);
}

export function GetWorkspacePath() {
  return window['go']['workspace']['WorkspaceService']['GetWorkspacePath']();
}

export function ImportFileToFolderInWorkspace(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['ImportFileToFolderInWorkspace'](arg1, arg2);
}

export function ImportFileToWorkspace(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['ImportFileToWorkspace'](arg1, arg2);
}

export function ListActiveConnections() {
  return window['go']['workspace']['WorkspaceService']['ListActiveConnections']();
}

export function ListFiles() {
  return window['go']['workspace']['WorkspaceService']['ListFiles']();
}

export function NewProject(arg1) {
  return window['go']['workspace']['WorkspaceService']['NewProject'](arg1);
}

export function Paste(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['Paste'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['workspace']['WorkspaceService']['ReadFile'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['RenameItem'](arg1, arg2);
}

export function SaveJsonFile(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['SaveJsonFile'](arg1, arg2);
}

export function SaveJsonToPath(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['SaveJsonToPath'](arg1, arg2);
}

export function SendSocketData(arg1, arg2, arg3) {
  return window['go']['workspace']['WorkspaceService']['SendSocketData'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['workspace']['WorkspaceService']['SetContext'](arg1);
}

export function ShowInExplorer(arg1) {
  return window['go']['workspace']['WorkspaceService']['ShowInExplorer'](arg1);
}

export function UploadConfig(arg1) {
  return window['go']['workspace']['WorkspaceService']['UploadConfig'](arg1);
}
