// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1) {
  return window['go']['workspace']['WorkspaceService']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['workspace']['WorkspaceService']['DeleteFile'](arg1);
}

export function DowloadConfig() {
  return window['go']['workspace']['WorkspaceService']['DowloadConfig']();
}

export function GetWorkspacePath() {
  return window['go']['workspace']['WorkspaceService']['GetWorkspacePath']();
}

export function ImportFile(arg1, arg2) {
  return window['go']['workspace']['WorkspaceService']['ImportFile'](arg1, arg2);
}

export function ListFiles() {
  return window['go']['workspace']['WorkspaceService']['ListFiles']();
}

export function NewProject(arg1) {
  return window['go']['workspace']['WorkspaceService']['NewProject'](arg1);
}

export function Paste() {
  return window['go']['workspace']['WorkspaceService']['Paste']();
}

export function ReadFile(arg1) {
  return window['go']['workspace']['WorkspaceService']['ReadFile'](arg1);
}

export function SetClipboard(arg1) {
  return window['go']['workspace']['WorkspaceService']['SetClipboard'](arg1);
}

export function SetContext(arg1) {
  return window['go']['workspace']['WorkspaceService']['SetContext'](arg1);
}

export function ShowInExplorer(arg1) {
  return window['go']['workspace']['WorkspaceService']['ShowInExplorer'](arg1);
}
