// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsername() {
  return window['go']['user']['UserService']['GetUsername']();
}

export function SendLoginCommand() {
  return window['go']['user']['UserService']['SendLoginCommand']();
}
