// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ShowInfoDialog() {
  return window['go']['main']['App']['ShowInfoDialog']();
}
