// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectFileToExport(arg1) {
  return window['go']['main']['App']['SelectFileToExport'](arg1);
}

export function SelectFileToImport() {
  return window['go']['main']['App']['SelectFileToImport']();
}

export function ShowErrorDialog(arg1) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1);
}

export function ShowInfoDialog() {
  return window['go']['main']['App']['ShowInfoDialog']();
}

export function ShowQuestionDialog(arg1) {
  return window['go']['main']['App']['ShowQuestionDialog'](arg1);
}
