// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContext():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectFileToExport(arg1:string):Promise<string>;

export function SelectFileToImport():Promise<string>;

export function ShowInfoDialog():Promise<void>;
