// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFileToExport(arg1:string):Promise<string>;

export function SelectFileToImport():Promise<string>;

export function ShowErrorDialog(arg1:string):Promise<void>;

export function ShowInfoDialog(arg1:string):Promise<void>;

export function ShowQuestionDialog(arg1:string):Promise<void>;
